trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: VSTest@2
  continueOnError: true
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: BuildQualityChecks@8
  inputs:
    checkWarnings: true
    warningFailOption: 'build'
    checkCoverage: false
    coverageFailOption: 'build'
    coverageType: 'blocks'   
- task: CopyFiles@2
  inputs:
    SourceFolder: $(buildPath) 
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Aino.io'
    publishLocation: 'Container'
