trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildPath: $(Build.SourcesDirectory)\AinoAgent\bin\Release\

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: VSTest@2
  continueOnError: true
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: BuildQualityChecks@8
  inputs:
    checkWarnings: true
    warningFailOption: 'build'
    checkCoverage: false
    coverageFailOption: 'build'
    coverageType: 'blocks'   
# Package a project
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'AinoAgent/*.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
# Push a project
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '404dd184-ce9e-4081-aae1-544c7f8b94df/e0235388-55a2-40f2-8d91-cea321e687b8'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Aino.io'
    publishLocation: 'Container'
